name: Backend CI

on:
  push:
    paths:
      - 'Backend/**'
      - '.github/workflows/backend.yml'
  pull_request:
    paths:
      - 'Backend/**'
      - '.github/workflows/backend.yml'

permissions:
  contents: read

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint import & syntax
        run: |
          python -m py_compile $(git ls-files '*.py')

      - name: Build Docker image
        run: |
          docker build -t backend-ci .

      - name: Start app for smoke test
        run: |
          docker run -d -p 8000:8000 --name backend backend-ci
          sleep 5
          curl -f http://localhost:8000/ || curl -f http://localhost:8000/health || (docker logs backend && exit 1)

      - name: Upload Docker image as artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-image-metadata
          path: |
            Dockerfile
            requirements.txt
            script.py

